# Generated by Django 4.2.27 on 2025-12-24 10:27

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="عنوان الترنيمة"),
                ),
                (
                    "anthropological_keywords",
                    models.CharField(
                        help_text="افصل الكلمات بفواصل",
                        max_length=500,
                        verbose_name="كلمات مفتاحية أنثروبولوجية",
                    ),
                ),
                (
                    "theological_keywords",
                    models.CharField(
                        help_text="افصل الكلمات بفواصل",
                        max_length=500,
                        verbose_name="كلمات مفتاحية لاهوتية",
                    ),
                ),
                ("lyrics", models.TextField(verbose_name="كلمات الترنيمة")),
                (
                    "powerpoint",
                    models.FileField(
                        upload_to="powerpoints/", verbose_name="ملف PowerPoint"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
