# Generated by Django 4.2.27 on 2025-12-24 12:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("songs", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="song",
            name="powerpoint",
        ),
        migrations.AddField(
            model_name="song",
            name="powerpoint_file",
            field=models.FileField(blank=True, null=True, upload_to="powerpoints/"),
        ),
        migrations.AddField(
            model_name="song",
            name="powerpoint_url",
            field=models.URLField(blank=True, null=True, verbose_name="PowerPoint URL"),
        ),
    ]
